### ISSUE TITLE
"Failed to minify the bundle" error on build 

### ISSUE THREAD

**Issue by gkverma** [microsoft/OCR-Form-Tools#406] opened 2020-07-13 11:03 UTC
**Describe the bug**
"Failed to minify the bundle" error on build 

**To Reproduce**
1. git clone https://github.com/Microsoft/OCR-Form-Tools.git
2. cd OCR-Form-Tools
3. npm install
4. npm run build

**Expected behavior**
Production build should be built

**Screenshots**

![image](https://user-images.githubusercontent.com/22412076/87297696-7d4f4e80-c526-11ea-8dac-8cec72f5750f.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - npm version : 6.10.2

**Additional context**
Add any other context about the problem here. e.g, your Azure Resource region

**Comment by alex-krasn** [comment] 2020-07-13 22:34
@gkverma Thank you for your response. We're working on resolving npm the issue. Meanwhile, you can use **yarn** and try to run ```yarn install```. This should resolve the issue. Please let us know if the problem is still present.

**Closed** 2020-07-15 14:43 UTC
